use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Tell Cargo to rerun this build script if assignment files change
    println!("cargo:rerun-if-changed=src/assignments/");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let assignments_dir = Path::new("src/assignments");

    // Find all assignment_*.rs files
    let mut assignment_days = Vec::new();

    if let Ok(entries) = fs::read_dir(assignments_dir) {
        for entry in entries {
            if let Ok(entry) = entry {
                let file_name = entry.file_name();
                let file_name_str = file_name.to_string_lossy();

                // Match assignment_N.rs pattern
                if file_name_str.starts_with("assignment_") && file_name_str.ends_with(".rs") {
                    let day_str = file_name_str
                        .strip_prefix("assignment_")
                        .and_then(|s| s.strip_suffix(".rs"));

                    if let Some(day_str) = day_str {
                        if let Ok(day) = day_str.parse::<u32>() {
                            assignment_days.push(day);
                        }
                    }
                }
            }
        }
    }

    // Sort the days to ensure consistent ordering
    assignment_days.sort();

    // Calculate relative path from OUT_DIR to src/assignments
    // OUT_DIR is typically target/debug/build/crate-hash/out/
    // We need to go up to the manifest dir, then to src/assignments
    let _out_path_obj = Path::new(&out_dir);
    let manifest_path_obj = Path::new(&manifest_dir);

    // Generate module declarations with absolute paths
    let module_declarations: String = assignment_days
        .iter()
        .map(|day| {
            let assignment_file = manifest_path_obj
                .join("src")
                .join("assignments")
                .join(format!("assignment_{}.rs", day));
            format!(
                "#[path = r#\"{}\"#]\nmod assignment_{};\n",
                assignment_file.display(),
                day
            )
        })
        .collect();

    // Generate the macro invocation with day numbers
    let days_str = assignment_days
        .iter()
        .map(|d| d.to_string())
        .collect::<Vec<_>>()
        .join(", ");

    let generated_code = format!(
        "// Auto-generated by build.rs - do not edit manually\n\
         // Module declarations:\n\
         {}\n\
         // Generate get_assignments function\n\
         include_assignments!({});\n",
        module_declarations, days_str
    );

    // Write to OUT_DIR
    let out_path = Path::new(&out_dir).join("assignments.rs");
    fs::write(&out_path, generated_code).unwrap();
}
